openapi: "3.0.1"
info:
  title: "Sample API VPC Link"
  version: "2.0.0"

paths:
  /test:
    get:
      responses:
        default:
          description: "Default response for GET /test"
      x-amazon-apigateway-integration:
        # Sample REST API integration with VPC Link
        connectionId: "$${stageVariables.vpc_link}"
        httpMethod: "GET"
        uri: "https://$${stageVariables.url}/test/default"
        responses:
          default:
            statusCode: "200"
        connectionType: "VPC_LINK"
        passthroughBehavior: "when_no_templates"
        type: "http"

components:
  securitySchemes: {}