openapi: "3.0.1"
info:
  title: "Sample API Rest Lambda"
  version: "2.0.0"

paths:
  /test:
    get:
      responses:
        default:
          description: "Default response for GET /test"
      x-amazon-apigateway-integration:
        # Sample REST API integration with SQS and Custom Parameters
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "${sqs_queue_endpoint}" # incoming value should have format: 123456789012:MyQueue, see aws.custom_parameters on vars/apigw/apis-<env>.yaml
        credentials: "${sqs_queue_role_arn}" # incoming value should have format: arn:aws:iam::123456789012:role/MyRole, see aws.custom_parameters on vars/apigw/apis-<env>.yaml
        connectionType: "INTERNET"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: "CONVERT_TO_TEXT"

components:
  securitySchemes: {}